### ISSUE TITLE
Error after upgrade to 0.6.0

### ISSUE THREAD

**Issue by cameron-emburse** [Tivix/django-cron#245]
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django_cron/management/commands/runcrons.py", line 45, in handle
    crons_to_run = [get_class(x) for x in cron_class_names]
  File "/usr/local/lib/python3.9/site-packages/django_cron/management/commands/runcrons.py", line 45, in <listcomp>
    crons_to_run = [get_class(x) for x in cron_class_names]
  File "/usr/local/lib/python3.9/site-packages/django_cron/__init__.py", line 33, in get_class
    m = __import__(module)
  File "/usr/local/lib/python3.9/site-packages/django_cron/cron.py", line 3, in <module>
    from django_common.helper import send_mail
ModuleNotFoundError: No module named 'django_common'
```

This line should have been removed according to the changelog from 0.5.1 to 0.6.0, but the line is there when I install 0.6.0 from pip...

Django version is 3.2.24

**Comment by jorenham** [comment]
This project appears to be abandoned. Feel free to use [my fork](https://github.com/jorenham/django-cron), which includes a fix for this.
