### ISSUE TITLE
ImportError: No module named 'base'

### ISSUE THREAD

**Issue by Speenah** [Tivix/django-cron#45]
I'm getting a really weird error whenever I try to do 'manage.py runcrons'.

```
>manage.py runcrons
Traceback (most recent call last):
  File "..\project\django_cron\__init__.py", line 181, in get_lock_class
    return get_class(name)
  File "..\project\django_cron\__init__.py", line 22, in get_class
    m = __import__(module)
  File "..\project\django_cron\backends\lock\cache.py", line 1, in <module>
    from base import DjangoCronJobLock
ImportError: No module named 'base'
```
I've tried installing through pip, downloading the repo and manually putting it in the project, and changing cache.py line 1 to
```
from ..base import DjangoCronJobLock
```
with no luck. I'm using Django 1.7.3 and Python 3.4.1.
Any thoughts?

**Comment by fedeverdini** [comment]
I have the same problem.

Try this:

```python
from django_cron.backends.lock.base import DjangoCronJobLock
```

It's not the best solution but it works.

**Comment by dfryta** [comment]
Thanks! Fixed.
