### ISSUE TITLE
ImportError: No module named 'django-cron'

### ISSUE THREAD

**Issue by xujipm** [Tivix/django-cron#76]
after `pip install django-cron` ,i hvae add `django-cron` to my Django settings `INSTALLED_APPS`

but there is some trouble when I run `python manage.py migrate django_cron`  

```
$ python manage.py shellpython manage.py migrate django_cron
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "D:\Python64\Anaconda3\lib\site-packages\django\core\management\__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "D:\Python64\Anaconda3\lib\site-packages\django\core\management\__init__.py", line 327, in execute
    django.setup()
  File "D:\Python64\Anaconda3\lib\site-packages\django\__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "D:\Python64\Anaconda3\lib\site-packages\django\apps\registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "D:\Python64\Anaconda3\lib\site-packages\django\apps\config.py", line 90, in create
    module = import_module(entry)
  File "D:\Python64\Anaconda3\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 956, in _find_and_load_unlocked
ImportError: No module named 'django-cron'
```

**Comment by craiglabenz** [comment]
Make sure you add `django_cron` to your `INSTALLED_APPS`, not `django-cron`.

**Comment by memmott** [comment]
@xujipm did this work for you?

**Comment by Satish1097** [comment]
I'm getting the same error and I didn't get solution
